package ee.golive.finance.domain;

/**
 * Defines types of cash flow that represent different types of
 * movement of the money related to a portfolio.
 *
 * @author Taavi Ilves, Golive, ilves.taavi@gmail.com
 */
public enum FlowType {

    /**
     * External cash flows are defined as cash, securities, or assets
     * that enter or exit a portfolio (capital additions or withdrawals)
     * and are generally client-driven. In context of this library deposits
     * or withdrawals.
     */
    EXTERNAL,

    /**
     * Internal cash flows are defined as cash cash, securities, or assets
     * that are generated by the portfolio i.e dividends, interests.
     */
    INTERNAL,

    /**
     * Other cash flows are used to represent cash flows inside the portfolio
     * i.e buying assets, taxes, service charges.
     */
    OTHER
}
